// Code generated by tygo. DO NOT EDIT.
// Source: services/api/internal/apitypes. Regenerate with `pnpm types:generate`.

//////////
// source: types.go
/*
Package apitypes holds the JSON request and response shapes of the HTTP API.
TypeScript types in packages/types are generated from this package with
tygo (`pnpm types:generate`); edit here, not in the generated file.
*/

export interface ErrorResponse {
  error: string;
}
export interface StatusResponse {
  status: string;
}
export interface User {
  id: string;
  email: string;
  displayName: string;
}
export interface MagicLinkRequest {
  email: string;
}
export interface VerifyLoginCodeRequest {
  email: string;
  code: string;
}
export type ExchangeState = string;
export const ExchangeStateDraft: ExchangeState = "draft";
export const ExchangeStateOpen: ExchangeState = "open";
export const ExchangeStateActive: ExchangeState = "active";
export const ExchangeStateCompleted: ExchangeState = "completed";
/**
 * ExchangeMember is a user who has joined an exchange. DisplayName is empty
 * until the user sets one.
 */
export interface ExchangeMember {
  userId: string;
  email: string;
  displayName: string;
  isOrganizer: boolean;
}
export interface Exchange {
  id: string;
  organizerId: string;
  name: string;
  description: string;
  /**
   * Calendar date, YYYY-MM-DD.
   */
  exchangeDate: string;
  budgetCents?: number | null;
  state: ExchangeState;
  members: ExchangeMember[];
}
/**
 * ListExchangeInvitesResponse holds the invites that have been neither accepted
 * nor declined. Only the organizer of an exchange may read them.
 */
export interface ListExchangeInvitesResponse {
  inviteEmails: string[];
}
export interface CreateExchangeRequest {
  name: string;
  description: string;
  /**
   * Calendar date, YYYY-MM-DD.
   */
  exchangeDate: string;
  budgetCents?: number | null;
  inviteEmails: string[];
}
export type UpdateExchangeRequest = CreateExchangeRequest;
export interface ListExchangesResponse {
  exchanges: Exchange[];
}
/**
 * Invite is a pending invite for the logged-in user's email.
 */
export interface Invite {
  exchangeId: string;
  exchangeName: string;
  /**
   * Calendar date, YYYY-MM-DD.
   */
  exchangeDate: string;
  organizerName: string;
  organizerEmail: string;
  invitedAt: string;
}
export interface ListInvitesResponse {
  invites: Invite[];
}
